### ISSUE TITLE
Shallow cloning possible? Depth option undocumented?

### ISSUE THREAD

**Issue by katrinleinweber** [laggingreflex/gfork#4]
Hello :-)  I noticed that ["depth" occurs several times in the code](https://github.com/laggingreflex/gfork/search?utf8=%E2%9C%93&q=depth&type=), but [the ReadMe](https://github.com/laggingreflex/gfork#usage) doesn't mention that, nor "shallow". In case that is indented to be possible, how can one use it?

I tried `gfork --edit-config --depth 2` in macOS 10.13.4's Terminal right after `npm install -g gfork`, but got:

```
/usr/local/lib/node_modules/gfork/utils/child-process.js:11
    opts = {...opts, capture: ['stdout', 'stderr'] };
            ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/gfork/utils/index.js:1:25)
```

I'd be happy to start using gforks, if shallow cloning would be possible, either with a sub command, option, or if `--depth=N` is passed through to git itself. Thanks for any hints here :-)

**Comment by laggingreflex** [comment]
Hm I think I did add `--depth` feature at one point, exactly for shallow cloning. But don't remember using it much, so if you find an issue please let me know. It should work just like how you tried to use it. 

As for the error it's due to old version of node (that doesn't support object rest-spread). Please use Node v9+.

**Comment by katrinleinweber** [comment]
Thanks for https://github.com/laggingreflex/gfork/commit/dc536d80dd6a9fc9efa97c3c1f4f9547aebb8c16 :-)
