### ISSUE TITLE
Cuts repo name off at .

### ISSUE THREAD

**Issue by katrinleinweber** [laggingreflex/gfork#6]
When trying gfork 0.11.0 on a GitHub Pages repo (`USER/PROJECT.github.com` or `….io`), it truncates the repo name to `PROJECT`.

I noticed this when cloning from the `hyperspy` & `hyperspy.github.com` from the [hyperspy org](https://github.com/hyperspy/) and it asked me about `Non-empty directory` on the second repo.

**Comment by laggingreflex** [comment]
Should be fixed now, please try v0.14.0
